version: '3'
services:
  irene-mic-client:
    container_name: irene-mic-client
    image: firefly27/irene-mic-client
    devices:
      - /dev/snd:/dev/snd
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/asound.conf:/etc/asound.conf
      - ./options.json:/options.json
      - ./options_telegrambot.json:/options_telegrambot.json
    restart: 'unless-stopped'
    # command: python run_remote_telegrambot.py
