version: '3'
services:
  irene-mic-client:
    container_name: irene-mic-client
    image: ss
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./options.json:/options.json
      - ./options_telegrambot.json:/options_telegrambot.json
    restart: 'unless-stopped'
    # command: python run_remote_telegrambot.py
